const express=require("express"),path=require("path"),Database=require("better-sqlite3"),PDFDocument=require("pdfkit");
const app=express(),PORT=process.env.PORT||3000,db=new Database(path.join(__dirname,"zomurud.db"));
db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name_ar TEXT,name_en TEXT,category TEXT,price REAL,compare_price REAL,stock INTEGER,description_ar TEXT,description_en TEXT,image TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE,customer_name TEXT,phone TEXT,city TEXT,notes TEXT,items_json TEXT,total REAL,status TEXT DEFAULT 'NEW',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){let a=require("./seed.json");let q=db.prepare("INSERT INTO products(name_ar,name_en,category,price,compare_price,stock,description_ar,description_en,image) VALUES(?,?,?,?,?,?,?,?,?)");a.forEach(p=>q.run(p[0],p[1],p[2],p[3],p[4],p[5],"حلول عرض احترافية من الزمرد.","Professional ZOMURUD display solution.",""))}
app.use(express.json({limit:"5mb"}));app.use(express.static(path.join(__dirname,"public")));
app.get("/api/products",(q,s)=>s.json(db.prepare("SELECT * FROM products WHERE active=1 ORDER BY id DESC").all()));
app.get("/api/stats",(q,s)=>s.json({revenue:db.prepare("SELECT COALESCE(SUM(total),0) x FROM orders WHERE status!='CANCELLED'").get().x,orders:db.prepare("SELECT COUNT(*) x FROM orders").get().x,customers:db.prepare("SELECT COUNT(DISTINCT phone) x FROM orders").get().x,products:db.prepare("SELECT COUNT(*) x FROM products WHERE active=1").get().x,low:db.prepare("SELECT COUNT(*) x FROM products WHERE active=1 AND stock<=3").get().x}));
app.post("/api/products",(q,s)=>{let p=q.body;if(!p.name_ar||!p.name_en||!p.category||Number(p.price)<0)return s.status(400).json({error:"بيانات المنتج ناقصة"});let r=db.prepare("INSERT INTO products(name_ar,name_en,category,price,compare_price,stock,description_ar,description_en,image) VALUES(?,?,?,?,?,?,?,?,?)").run(p.name_ar,p.name_en,p.category,+p.price,+p.compare_price||0,+p.stock||0,p.description_ar||"",p.description_en||"",p.image||"");s.json({id:r.lastInsertRowid})});
app.put("/api/products/:id",(q,s)=>{let p=q.body;db.prepare("UPDATE products SET name_ar=?,name_en=?,category=?,price=?,compare_price=?,stock=?,description_ar=?,description_en=?,image=? WHERE id=?").run(p.name_ar,p.name_en,p.category,+p.price,+p.compare_price||0,+p.stock||0,p.description_ar||"",p.description_en||"",p.image||"",q.params.id);s.json({ok:true})});
app.delete("/api/products/:id",(q,s)=>{db.prepare("UPDATE products SET active=0 WHERE id=?").run(q.params.id);s.json({ok:true})});
app.get("/api/orders",(q,s)=>s.json(db.prepare("SELECT * FROM orders ORDER BY id DESC").all()));
app.post("/api/orders",(q,s)=>{let {customer_name,phone,city,notes,items,total}=q.body;if(!customer_name||!phone||!items?.length)return s.status(400).json({error:"البيانات ناقصة"});let no="ZM-"+Date.now().toString().slice(-9);let tx=db.transaction(()=>{for(let i of items){let p=db.prepare("SELECT stock FROM products WHERE id=? AND active=1").get(i.id);if(!p||p.stock<i.qty)throw Error("المخزون غير كاف");}for(let i of items)db.prepare("UPDATE products SET stock=stock-? WHERE id=?").run(i.qty,i.id);return db.prepare("INSERT INTO orders(order_no,customer_name,phone,city,notes,items_json,total) VALUES(?,?,?,?,?,?,?)").run(no,customer_name,phone,city||"",notes||"",JSON.stringify(items),+total||0)});try{tx();s.json({order_no:no})}catch(e){s.status(400).json({error:e.message})}});
app.patch("/api/orders/:id",(q,s)=>{let a=["NEW","CONFIRMED","PROCESSING","READY","SHIPPED","DELIVERED","CANCELLED"];if(!a.includes(q.body.status))return s.status(400).json({error:"invalid status"});db.prepare("UPDATE orders SET status=? WHERE id=?").run(q.body.status,q.params.id);s.json({ok:true})});
app.get("/api/invoice/:id",(q,s)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(q.params.id);if(!o)return s.status(404).send("Not found");let d=new PDFDocument({size:"A4",margin:45});s.setHeader("Content-Type","application/pdf");s.setHeader("Content-Disposition",`inline; filename="${o.order_no}.pdf"`);d.pipe(s);d.fontSize(25).text("ZOMURUD");d.fontSize(11).fillColor("#555").text("الزمرد | Sales Invoice");d.fillColor("#111").text(`Invoice: ${o.order_no}`).text(`Date: ${new Date(o.created_at).toLocaleDateString("en-GB")}`).moveDown();d.text(`Customer: ${o.customer_name}`).text(`Phone: ${o.phone}`).text(`City: ${o.city||""}`).moveDown();let y=d.y+15;d.text("Product",55,y).text("Qty",350,y).text("Unit",405,y).text("Total",480,y);y+=25;for(let i of JSON.parse(o.items_json)){d.text(String(i.name).slice(0,38),55,y).text(String(i.qty),350,y).text(`AED ${(+i.price).toFixed(2)}`,405,y).text(`AED ${(+i.price*i.qty).toFixed(2)}`,480,y);y+=25}d.moveDown(2).fontSize(15).text(`TOTAL: AED ${(+o.total).toFixed(2)}`,370,d.y,{align:"right"});d.end()});
app.get("/admin",(q,s)=>s.sendFile(path.join(__dirname,"public/admin.html")));app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"public/index.html")));app.listen(PORT,()=>console.log("ZOMURUD "+PORT));